# Generated by Django 2.2.1 on 2019-06-07 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pic_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('category', models.CharField(blank=True, max_length=200)),
                ('publish', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
